### ISSUE TITLE
Basis search location to standard location

### ISSUE THREAD

**Issue by wavefunction91** [liresearchgroup/chronusq#5]
As of now, ChronusQ looks for a basis set file in the directory that it is called from. This should be changed so that the default search location is in the standard location specified by BASIS_PATH. This PP variable is already set by cmake, it just needs to be merged into the code.

If the basis is not found in BASIS_PATH, search the current directory. If not found there, throw an error.

**Comment by liresearchgroup** [comment]
Filled by @wavefunction91
